---
type: wordpress
hooks:
  post-start:
    - exec: "[ -f ./$DDEV_DOCROOT/index.php ] || wp core download --version=6.0.4"
    - exec: "wp core install --url='$DDEV_PRIMARY_URL' --title='Vulnerability Testbench' --admin_user=superadmin --admin_password=password --admin_email=admin@example.com"
    - exec: "wp user import-csv ./$DDEV_DOCROOT/.ddev/users.csv --skip-update"
    - exec: "wp user update superadmin --display_name='Super Admin'"
    - exec: "wp plugin activate wpscan-poc-helper"
